### ISSUE TITLE
Review default settings for filters

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/kartograf#59]
We should review the current default filter settings, especially in light of the OpenFE RFE Protocols.

Specifically we should look at the following filters:
  - Ring breaking settings
  - Hybridization change
  - Hydrogen to heavy atom (aiming to turn it off)

To achieve this we should:
  - Map plb v0.3 (and/or industry benchmarks) and run on edges that are different
  - Run both “same edges” and “new network”

**Comment by IAlibay** [comment]
@jthorton could you write some outcomes of this work? i.e. it's closed - what were your findings and what will you do next.

**Comment by jthorton** [comment]
Following the filter investigation we plan on:
- changing the hydrogen to heavy atom mapping to `False` by default which has no impact on performance but makes the visualisation of the mapping match what is used in practice as the hybrid topology protocol silently removed the mappings.
- For the fused ring changes we saw minimal impact on performance across the 5 edges which had new mappings across all systems in the MST PLB networks. We plan to test this on more transformations by creating a maximally connected network for hif2a and looking at fused ring edges and some ASAP networks from Jenke which seem to break unless this method is used.
- The hybridization filter needs to be refined as it was unexpectedly changing mappings due to the hybridization assigned by rdkit to aromatic ether linker groups, which caused very large perturbations.
